title: Tian Tian / 田甜
author: karottenfruchtladen
subtitle: Something mildly good.

url: "https://therealtiantian.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Film Reviews"
   absolute-link: "https://www.imdb.com/user/ur133207107/reviews/?ref_=up_ururv_sm"   
 - name: "Magazine Works"
   link: "/assets/portfolio.pdf"
 - name: "Resume"
   link: "/assets/cv.pdf"
